[package]
name = "burn-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.17.0", features = ["train", "wgpu", "vision", "metal"] }

[build-dependencies]
burn-import = "0.17.0"
